### ISSUE TITLE
Reason for course conflict believes there is no assigned teacher when there is 

### ISSUE THREAD

**Issue by abax17** [DrewUniversityCS/CS3#56]
![image](https://user-images.githubusercontent.com/78123718/116020398-2f6a8980-a614-11eb-9fa2-29412eba2996.png)
![image](https://user-images.githubusercontent.com/78123718/116020428-3b564b80-a614-11eb-8466-6e8d3bb9001c.png)

**Comment by NullDefault** [comment]
Language should be updated: this is expected behavior "the course is not taught by the specified teacher" means the course has a positive preference with a teacher, and that teacher is not assigned to it. We should probably make the preferences visible somewhere in the schedule view @malminawi
